"""transactions table

Revision ID: 124196a68521
Revises: ecfe6781ea8f
Create Date: 2026-02-11 17:54:29.476723

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "124196a68521"
down_revision: Union[str, Sequence[str], None] = "ecfe6781ea8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- AUTOMATED HEADER ---
    conn = op.get_bind()
    # Ensure the extension exists before any indices try to use it
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("reference", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "checkout_request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "merchant_request_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False
        ),
        sa.Column(
            "mpesa_receipt_number", sqlmodel.sql.sqltypes.AutoString(), nullable=True
        ),
        sa.Column("result_code", sa.Integer(), nullable=False),
        sa.Column("result_desc", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("transaction_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_transactions_checkout_request_id"),
        "transactions",
        ["checkout_request_id"],
        unique=True,
    )
    op.create_index(op.f("ix_transactions_id"), "transactions", ["id"], unique=False)
    op.create_index(
        op.f("ix_transactions_merchant_request_id"),
        "transactions",
        ["merchant_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_mpesa_receipt_number"),
        "transactions",
        ["mpesa_receipt_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_phone_number"),
        "transactions",
        ["phone_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_reference"), "transactions", ["reference"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_reference"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_phone_number"), table_name="transactions")
    op.drop_index(
        op.f("ix_transactions_mpesa_receipt_number"), table_name="transactions"
    )
    op.drop_index(
        op.f("ix_transactions_merchant_request_id"), table_name="transactions"
    )
    op.drop_index(op.f("ix_transactions_id"), table_name="transactions")
    op.drop_index(
        op.f("ix_transactions_checkout_request_id"), table_name="transactions"
    )
    op.drop_table("transactions")
    # ### end Alembic commands ###
