"""transaction status

Revision ID: 21ac4bbb4dad
Revises: 7de9ee3ea896
Create Date: 2026-02-15 18:39:51.240732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21ac4bbb4dad"
down_revision: Union[str, Sequence[str], None] = "7de9ee3ea896"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- AUTOMATED HEADER ---
    conn = op.get_bind()
    # Ensure the extension exists before any indices try to use it
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=True,
        ),
    )
    op.create_index(
        op.f("ix_transactions_status"), "transactions", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transactions_status"), table_name="transactions")
    op.drop_column("transactions", "status")
    # ### end Alembic commands ###
