"""transactions table reference_id

Revision ID: 29d3eaaf1f36
Revises: 124196a68521
Create Date: 2026-02-11 18:01:23.668556

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "29d3eaaf1f36"
down_revision: Union[str, Sequence[str], None] = "124196a68521"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- AUTOMATED HEADER ---
    conn = op.get_bind()
    # Ensure the extension exists before any indices try to use it
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("reference_id", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    )
    op.drop_index(
        op.f("ix_transactions_checkout_request_id"), table_name="transactions"
    )
    op.drop_index(
        op.f("ix_transactions_merchant_request_id"), table_name="transactions"
    )
    op.drop_index(
        op.f("ix_transactions_mpesa_receipt_number"), table_name="transactions"
    )
    op.drop_index(op.f("ix_transactions_phone_number"), table_name="transactions")
    op.drop_index(op.f("ix_transactions_reference"), table_name="transactions")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_transactions_reference"), "transactions", ["reference"], unique=False
    )
    op.create_index(
        op.f("ix_transactions_phone_number"),
        "transactions",
        ["phone_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_mpesa_receipt_number"),
        "transactions",
        ["mpesa_receipt_number"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_merchant_request_id"),
        "transactions",
        ["merchant_request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_transactions_checkout_request_id"),
        "transactions",
        ["checkout_request_id"],
        unique=True,
    )
    op.drop_column("transactions", "reference_id")
    # ### end Alembic commands ###
