"""removes refence id

Revision ID: a4244fc1ba7c
Revises: 29d3eaaf1f36
Create Date: 2026-02-11 18:19:09.904406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "a4244fc1ba7c"
down_revision: Union[str, Sequence[str], None] = "29d3eaaf1f36"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- AUTOMATED HEADER ---
    conn = op.get_bind()
    # Ensure the extension exists before any indices try to use it
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("transactions", "reference_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transactions",
        sa.Column("reference_id", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
