"""database init

Revision ID: b7e7fb46f702
Revises:
Create Date: 2026-02-03 15:09:49.723863

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "b7e7fb46f702"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- AUTOMATED HEADER ---
    conn = op.get_bind()
    # Ensure the extension exists before any indices try to use it
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "authors",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("bio", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("profile_image", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "social_links", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_authors_id"), "authors", ["id"], unique=False)
    op.create_table(
        "services",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "provider",
            sa.Enum(
                "KRA",
                "NTSA",
                "DCI",
                "BRS",
                "HELB",
                "SHA",
                "IMMIGRATION",
                "LANDS",
                "CRS",
                name="serviceprovider",
            ),
            nullable=False,
        ),
        sa.Column(
            "category",
            sa.Enum(
                "TRANSPORT",
                "CIVIL_REG",
                "TAXATION",
                "BUSINESS",
                "EDUCATION",
                "HEALTH",
                "LEGAL",
                "LANDS",
                "IMMIGRATION",
                name="servicecategory",
            ),
            nullable=False,
        ),
        sa.Column("sub_category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("icon", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("description", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "seo_title", sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False
        ),
        sa.Column(
            "seo_description",
            sqlmodel.sql.sqltypes.AutoString(length=160),
            nullable=False,
        ),
        sa.Column(
            "requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("faqs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("pricing", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("estimated_time", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("available", sa.Boolean(), nullable=False),
        sa.Column("published", sa.Boolean(), nullable=False),
        sa.Column("searchable", sa.Boolean(), nullable=False),
        sa.Column("featured", sa.Boolean(), nullable=False),
        sa.Column("popularity_score", sa.Float(), nullable=True),
        sa.Column("schema_type", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
        sa.Column(
            "related_slugs", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_services_available"), "services", ["available"], unique=False
    )
    op.create_index(
        op.f("ix_services_category"), "services", ["category"], unique=False
    )
    op.create_index(
        op.f("ix_services_featured"), "services", ["featured"], unique=False
    )
    op.create_index(op.f("ix_services_id"), "services", ["id"], unique=False)
    op.create_index(op.f("ix_services_name"), "services", ["name"], unique=False)
    op.create_index(
        op.f("ix_services_popularity_score"),
        "services",
        ["popularity_score"],
        unique=False,
    )
    op.create_index(
        op.f("ix_services_provider"), "services", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_services_published"), "services", ["published"], unique=False
    )
    op.create_index(
        op.f("ix_services_searchable"), "services", ["searchable"], unique=False
    )
    op.create_index(op.f("ix_services_slug"), "services", ["slug"], unique=True)
    op.create_index(
        op.f("ix_services_sub_category"), "services", ["sub_category"], unique=False
    )
    op.create_index(
        "trgm_idx_service_name",
        "services",
        ["name"],
        unique=False,
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.create_table(
        "users",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("second_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("email", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("phone_number", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("contact_method", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "blog_posts",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("title", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("slug", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column(
            "excerpt", sqlmodel.sql.sqltypes.AutoString(length=250), nullable=False
        ),
        sa.Column("author_id", sa.Uuid(), nullable=False),
        sa.Column("image", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "seo_title", sqlmodel.sql.sqltypes.AutoString(length=60), nullable=False
        ),
        sa.Column(
            "seo_description",
            sqlmodel.sql.sqltypes.AutoString(length=160),
            nullable=False,
        ),
        sa.Column("content", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("faqs", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["author_id"],
            ["authors.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_blog_posts_author_id"), "blog_posts", ["author_id"], unique=False
    )
    op.create_index(op.f("ix_blog_posts_id"), "blog_posts", ["id"], unique=False)
    op.create_index(op.f("ix_blog_posts_slug"), "blog_posts", ["slug"], unique=True)
    op.create_table(
        "orders",
        sa.Column(
            "id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PAID",
                "IN_PROGRESS",
                "COMPLETED",
                "CANCELLED",
                name="orderstatus",
            ),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_orders_id"), "orders", ["id"], unique=False)
    op.create_index(
        op.f("ix_orders_service_id"), "orders", ["service_id"], unique=False
    )
    op.create_index(op.f("ix_orders_user_id"), "orders", ["user_id"], unique=False)
    op.create_table(
        "servicebloglink",
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("blog_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blog_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("service_id", "blog_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("servicebloglink")
    op.drop_index(op.f("ix_orders_user_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_service_id"), table_name="orders")
    op.drop_index(op.f("ix_orders_id"), table_name="orders")
    op.drop_table("orders")
    op.drop_index(op.f("ix_blog_posts_slug"), table_name="blog_posts")
    op.drop_index(op.f("ix_blog_posts_id"), table_name="blog_posts")
    op.drop_index(op.f("ix_blog_posts_author_id"), table_name="blog_posts")
    op.drop_table("blog_posts")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        "trgm_idx_service_name",
        table_name="services",
        postgresql_using="gin",
        postgresql_ops={"name": "gin_trgm_ops"},
    )
    op.drop_index(op.f("ix_services_sub_category"), table_name="services")
    op.drop_index(op.f("ix_services_slug"), table_name="services")
    op.drop_index(op.f("ix_services_searchable"), table_name="services")
    op.drop_index(op.f("ix_services_published"), table_name="services")
    op.drop_index(op.f("ix_services_provider"), table_name="services")
    op.drop_index(op.f("ix_services_popularity_score"), table_name="services")
    op.drop_index(op.f("ix_services_name"), table_name="services")
    op.drop_index(op.f("ix_services_id"), table_name="services")
    op.drop_index(op.f("ix_services_featured"), table_name="services")
    op.drop_index(op.f("ix_services_category"), table_name="services")
    op.drop_index(op.f("ix_services_available"), table_name="services")
    op.drop_table("services")
    op.drop_index(op.f("ix_authors_id"), table_name="authors")
    op.drop_table("authors")
    # ### end Alembic commands ###
