"""blogpost and service tables

Revision ID: bc8c01881f2b
Revises: 39c02b9fbc74
Create Date: 2026-01-24 18:23:52.018222

"""
from typing import Sequence, Union

from alembic import op
import sqlmodel
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'bc8c01881f2b'
down_revision: Union[str, Sequence[str], None] = '39c02b9fbc74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog_posts',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('author', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('published_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_date', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('image', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('excerpt', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seo_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seo_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('related_services', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_posts_slug'), 'blog_posts', ['slug'], unique=True)
    op.create_index(op.f('ix_orders_service_id'), 'orders', ['service_id'], unique=False)
    op.create_index(op.f('ix_orders_user_id'), 'orders', ['user_id'], unique=False)
    op.add_column('services', sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('sub_category', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('seo_title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('seo_description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('services', sa.Column('requirements', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('services', sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('services', sa.Column('pricing', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('services', sa.Column('estimated_time', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('services', 'service_name')
    op.drop_column('services', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('services', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('services', sa.Column('service_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('services', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('services', 'estimated_time')
    op.drop_column('services', 'pricing')
    op.drop_column('services', 'faqs')
    op.drop_column('services', 'requirements')
    op.drop_column('services', 'seo_description')
    op.drop_column('services', 'seo_title')
    op.drop_column('services', 'icon')
    op.drop_column('services', 'sub_category')
    op.drop_column('services', 'category')
    op.drop_column('services', 'provider')
    op.drop_column('services', 'name')
    op.drop_index(op.f('ix_orders_user_id'), table_name='orders')
    op.drop_index(op.f('ix_orders_service_id'), table_name='orders')
    op.drop_index(op.f('ix_blog_posts_slug'), table_name='blog_posts')
    op.drop_table('blog_posts')
    # ### end Alembic commands ###
