"""dialect aware models

Revision ID: ecfe6781ea8f
Revises: b7e7fb46f702
Create Date: 2026-02-04 21:18:25.807349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ecfe6781ea8f"
down_revision: Union[str, Sequence[str], None] = "b7e7fb46f702"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # --- AUTOMATED HEADER ---
    conn = op.get_bind()
    # Ensure the extension exists before any indices try to use it
    if conn.dialect.name == "postgresql":
        op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ------------------------

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "service_blog_links",
        sa.Column("service_id", sa.Uuid(), nullable=False),
        sa.Column("blog_id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"],
            ["blog_posts.id"],
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
        ),
        sa.PrimaryKeyConstraint("service_id", "blog_id"),
    )
    op.drop_table("servicebloglink")
    op.alter_column(
        "authors",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "blog_posts",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "users",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "services",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "orders",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "blog_posts",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.alter_column(
        "authors",
        "id",
        existing_type=sa.UUID(),
        server_default=sa.text("gen_random_uuid()"),
        existing_nullable=False,
    )
    op.create_table(
        "servicebloglink",
        sa.Column("service_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("blog_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["blog_id"], ["blog_posts.id"], name=op.f("servicebloglink_blog_id_fkey")
        ),
        sa.ForeignKeyConstraint(
            ["service_id"],
            ["services.id"],
            name=op.f("servicebloglink_service_id_fkey"),
        ),
        sa.PrimaryKeyConstraint(
            "service_id", "blog_id", name=op.f("servicebloglink_pkey")
        ),
    )
    op.drop_table("service_blog_links")
    # ### end Alembic commands ###
