// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: "http://localhost:8000" | (string & {});
};

/**
 * FAQ
 */
export type Faq = {
  /**
   * Q
   */
  q: string;
  /**
   * A
   */
  a: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * OrderRequestSchema
 */
export type OrderRequestSchema = {
  /**
   * Userid
   */
  userId: string;
  /**
   * Serviceid
   */
  serviceId: string;
  /**
   * Name
   */
  name: string;
  /**
   * Amount
   */
  amount: number;
};

/**
 * OrderStatus
 */
export type OrderStatus =
  | "Pending"
  | "Paid"
  | "In Progress"
  | "Completed"
  | "Cancelled";

/**
 * OrderUpdateSchema
 */
export type OrderUpdateSchema = {
  status: OrderStatus;
};

/**
 * Pricing
 */
export type Pricing = {
  /**
   * Governmentfee
   */
  governmentFee?: number;
  /**
   * Servicefee
   */
  serviceFee?: number;
  /**
   * Total
   */
  total?: number;
};

/**
 * ServiceCategory
 */
export type ServiceCategory =
  | "Transport & Motoring"
  | "Civil Registration"
  | "Taxation & KRA"
  | "Business & Industry"
  | "Education & Training"
  | "Health Services"
  | "Legal & Public Safety"
  | "Lands & Housing"
  | "Immigration & Foreign Affairs";

/**
 * ServiceCreateSchema
 */
export type ServiceCreateSchema = {
  /**
   * Name
   */
  name: string;
  /**
   * Slug
   */
  slug: string;
  provider: ServiceProvider;
  category: ServiceCategory;
  /**
   * Sub Category
   */
  sub_category: string;
  /**
   * Icon
   */
  icon: string;
  /**
   * Description
   */
  description: string;
  /**
   * Seo Title
   */
  seo_title: string;
  /**
   * Seo Description
   */
  seo_description: string;
  /**
   * Requirements
   */
  requirements: Array<string>;
  /**
   * Faqs
   */
  faqs: Array<Faq>;
  pricing: Pricing;
  /**
   * Estimated Time
   */
  estimated_time: string;
  /**
   * Available
   */
  available?: boolean;
  /**
   * Published
   */
  published?: boolean;
  /**
   * Featured
   */
  featured?: boolean;
  /**
   * Popularityscore
   */
  popularityScore?: number | null;
  /**
   * Schematype
   */
  schemaType?: string;
  /**
   * Relatedslugs
   */
  relatedSlugs?: Array<string> | null;
};

/**
 * ServiceProvider
 */
export type ServiceProvider =
  | "Kenya Revenue Authority"
  | "National Transport and Safety Authority"
  | "Directorate of Criminal Investigations"
  | "Business Registration Service"
  | "Higher Education Loans Board"
  | "Social Health Authority"
  | "Department of Immigration"
  | "Ministry of Lands"
  | "Civil Registration Services";

/**
 * ServiceRead
 *
 * The schema Next.js uses for pre-rendering.
 */
export type ServiceRead = {
  /**
   * Name
   */
  name: string;
  /**
   * Slug
   */
  slug: string;
  provider: ServiceProvider;
  category: ServiceCategory;
  /**
   * Subcategory
   */
  subCategory: string;
  /**
   * Icon
   */
  icon: string;
  /**
   * Description
   */
  description: string;
  /**
   * Seotitle
   */
  seoTitle: string;
  /**
   * Seodescription
   */
  seoDescription: string;
  /**
   * Requirements
   */
  requirements: Array<string>;
  /**
   * Faqs
   */
  faqs: Array<Faq>;
  pricing: Pricing;
  /**
   * Estimatedtime
   */
  estimatedTime: string;
  /**
   * Available
   */
  available: boolean;
  /**
   * Published
   */
  published: boolean;
  /**
   * Featured
   */
  featured?: boolean;
  /**
   * Popularityscore
   */
  popularityScore?: number | null;
  /**
   * Schematype
   */
  schemaType?: string;
  /**
   * Relatedslugs
   */
  relatedSlugs?: Array<string> | null;
  /**
   * Id
   */
  id: string;
};

/**
 * ServiceUpdateSchema
 */
export type ServiceUpdateSchema = {
  /**
   * Name
   */
  name?: string | null;
  /**
   * Slug
   */
  slug?: string | null;
  provider?: ServiceProvider | null;
  category?: ServiceCategory | null;
  /**
   * Sub Category
   */
  sub_category?: string | null;
  /**
   * Icon
   */
  icon?: string | null;
  /**
   * Description
   */
  description?: string | null;
  /**
   * Seo Title
   */
  seo_title?: string | null;
  /**
   * Seo Description
   */
  seo_description?: string | null;
  /**
   * Requirements
   */
  requirements?: Array<string> | null;
  /**
   * Faqs
   */
  faqs?: Array<Faq> | null;
  pricing?: Pricing | null;
  /**
   * Estimated Time
   */
  estimated_time?: string | null;
};

/**
 * StkRequest
 */
export type StkRequest = {
  /**
   * Phone
   */
  phone: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Reference
   */
  reference: string;
  /**
   * Description
   */
  description?: string;
};

/**
 * SuggestionsResponse
 */
export type SuggestionsResponse = {
  /**
   * N
   */
  n?: string | null;
  /**
   * S
   */
  s?: string | null;
  c?: ServiceCategory | null;
  /**
   * D
   */
  d?: string;
  /**
   * P
   */
  p: number | null;
};

/**
 * TransactionRead
 */
export type TransactionRead = {
  /**
   * Phonenumber
   */
  phoneNumber: string;
  /**
   * Amount
   */
  amount: number;
  /**
   * Reference
   */
  reference: string;
  /**
   * Checkoutrequestid
   */
  checkoutRequestId: string;
  /**
   * Merchantrequestid
   */
  merchantRequestId: string;
  /**
   * Mpesareceiptnumber
   */
  mpesaReceiptNumber?: string | null;
  /**
   * Resultcode
   */
  resultCode?: number;
  /**
   * Resultdesc
   */
  resultDesc?: string | null;
  status?: OrderStatus | null;
};

/**
 * UserCreateSchema
 */
export type UserCreateSchema = {
  /**
   * Firstname
   */
  firstName: string;
  /**
   * Secondname
   */
  secondName: string;
  /**
   * Email
   */
  email: string;
  /**
   * Phonenumber
   */
  phoneNumber: string;
  /**
   * Contactmethod
   */
  contactMethod: string;
};

/**
 * UserRead
 */
export type UserRead = {
  /**
   * Firstname
   */
  firstName: string;
  /**
   * Secondname
   */
  secondName: string;
  /**
   * Email
   */
  email: string;
  /**
   * Phonenumber
   */
  phoneNumber: string;
  /**
   * Contactmethod
   */
  contactMethod: string;
  /**
   * Id
   */
  id: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
};

export type GetTransApiV1PaymentsTransactionsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Checkout Request Id
     */
    checkout_request_id?: string;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/payments/transactions";
};

export type GetTransApiV1PaymentsTransactionsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTransApiV1PaymentsTransactionsGetError =
  GetTransApiV1PaymentsTransactionsGetErrors[keyof GetTransApiV1PaymentsTransactionsGetErrors];

export type GetTransApiV1PaymentsTransactionsGetResponses = {
  /**
   * Response Get Trans Api V1 Payments Transactions Get
   *
   * Successful Response
   */
  200: TransactionRead | Array<TransactionRead>;
};

export type GetTransApiV1PaymentsTransactionsGetResponse =
  GetTransApiV1PaymentsTransactionsGetResponses[keyof GetTransApiV1PaymentsTransactionsGetResponses];

export type InitiateStkPushApiV1PaymentsStkPushPostData = {
  body: StkRequest;
  path?: never;
  query?: never;
  url: "/api/v1/payments/stk-push";
};

export type InitiateStkPushApiV1PaymentsStkPushPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type InitiateStkPushApiV1PaymentsStkPushPostError =
  InitiateStkPushApiV1PaymentsStkPushPostErrors[keyof InitiateStkPushApiV1PaymentsStkPushPostErrors];

export type InitiateStkPushApiV1PaymentsStkPushPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PaymentsValidationApiV1PaymentsValidationPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/payments/validation";
};

export type PaymentsValidationApiV1PaymentsValidationPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PaymentsConfirmationApiV1PaymentsConfirmationPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/payments/confirmation";
};

export type PaymentsConfirmationApiV1PaymentsConfirmationPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type PaymentsStkCallbackApiV1PaymentsStkCallbackPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/payments/stk-callback";
};

export type PaymentsStkCallbackApiV1PaymentsStkCallbackPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type ReadUsersApiV1UsersGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * User Id
     */
    user_id?: string;
    /**
     * Email
     */
    email?: string;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/users/";
};

export type ReadUsersApiV1UsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ReadUsersApiV1UsersGetError =
  ReadUsersApiV1UsersGetErrors[keyof ReadUsersApiV1UsersGetErrors];

export type ReadUsersApiV1UsersGetResponses = {
  /**
   * Response Read Users Api V1 Users  Get
   *
   * Successful Response
   */
  200: UserRead | Array<UserRead>;
};

export type ReadUsersApiV1UsersGetResponse =
  ReadUsersApiV1UsersGetResponses[keyof ReadUsersApiV1UsersGetResponses];

export type CreateUserApiV1UsersRegisterPostData = {
  body: UserCreateSchema;
  path?: never;
  query?: never;
  url: "/api/v1/users/register";
};

export type CreateUserApiV1UsersRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateUserApiV1UsersRegisterPostError =
  CreateUserApiV1UsersRegisterPostErrors[keyof CreateUserApiV1UsersRegisterPostErrors];

export type CreateUserApiV1UsersRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOrdersApiV1OrdersFilteredGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * User Id
     */
    user_id?: string;
    status?: OrderStatus;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/orders/filtered";
};

export type GetOrdersApiV1OrdersFilteredGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrdersApiV1OrdersFilteredGetError =
  GetOrdersApiV1OrdersFilteredGetErrors[keyof GetOrdersApiV1OrdersFilteredGetErrors];

export type GetOrdersApiV1OrdersFilteredGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetOrderIdApiV1OrdersOrderIdGetData = {
  body?: never;
  path: {
    /**
     * Order Id
     */
    order_id: string;
  };
  query?: never;
  url: "/api/v1/orders/{order_id}";
};

export type GetOrderIdApiV1OrdersOrderIdGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetOrderIdApiV1OrdersOrderIdGetError =
  GetOrderIdApiV1OrdersOrderIdGetErrors[keyof GetOrderIdApiV1OrdersOrderIdGetErrors];

export type GetOrderIdApiV1OrdersOrderIdGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type CreateOrderApiV1OrdersCreatePostData = {
  body: OrderRequestSchema;
  path?: never;
  query?: never;
  url: "/api/v1/orders/create";
};

export type CreateOrderApiV1OrdersCreatePostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateOrderApiV1OrdersCreatePostError =
  CreateOrderApiV1OrdersCreatePostErrors[keyof CreateOrderApiV1OrdersCreatePostErrors];

export type CreateOrderApiV1OrdersCreatePostResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type UpdateOrderApiV1OrdersUpdateOrderIdPutData = {
  body: OrderUpdateSchema;
  path: {
    /**
     * Order Id
     */
    order_id: string;
  };
  query?: never;
  url: "/api/v1/orders/update/{order_id}";
};

export type UpdateOrderApiV1OrdersUpdateOrderIdPutErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateOrderApiV1OrdersUpdateOrderIdPutError =
  UpdateOrderApiV1OrdersUpdateOrderIdPutErrors[keyof UpdateOrderApiV1OrdersUpdateOrderIdPutErrors];

export type UpdateOrderApiV1OrdersUpdateOrderIdPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetServicesApiV1ServicesFilteredGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Category
     */
    category?: ServiceCategory | null;
    /**
     * Provider
     */
    provider?: ServiceProvider | null;
    /**
     * Skip
     */
    skip?: number;
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/services/filtered";
};

export type GetServicesApiV1ServicesFilteredGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetServicesApiV1ServicesFilteredGetError =
  GetServicesApiV1ServicesFilteredGetErrors[keyof GetServicesApiV1ServicesFilteredGetErrors];

export type GetServicesApiV1ServicesFilteredGetResponses = {
  /**
   * Response Get Services Api V1 Services Filtered Get
   *
   * Successful Response
   */
  200: Array<ServiceRead>;
};

export type GetServicesApiV1ServicesFilteredGetResponse =
  GetServicesApiV1ServicesFilteredGetResponses[keyof GetServicesApiV1ServicesFilteredGetResponses];

export type GetServiceBySlugApiV1ServicesBySlugSlugGetData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/api/v1/services/by-slug/{slug}";
};

export type GetServiceBySlugApiV1ServicesBySlugSlugGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetServiceBySlugApiV1ServicesBySlugSlugGetError =
  GetServiceBySlugApiV1ServicesBySlugSlugGetErrors[keyof GetServiceBySlugApiV1ServicesBySlugSlugGetErrors];

export type GetServiceBySlugApiV1ServicesBySlugSlugGetResponses = {
  /**
   * Successful Response
   */
  200: ServiceRead;
};

export type GetServiceBySlugApiV1ServicesBySlugSlugGetResponse =
  GetServiceBySlugApiV1ServicesBySlugSlugGetResponses[keyof GetServiceBySlugApiV1ServicesBySlugSlugGetResponses];

export type GetSearchManifestApiV1ServicesSearchManifestGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/services/search-manifest";
};

export type GetSearchManifestApiV1ServicesSearchManifestGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetSearchManifestApiV1ServicesSearchManifestGetError =
  GetSearchManifestApiV1ServicesSearchManifestGetErrors[keyof GetSearchManifestApiV1ServicesSearchManifestGetErrors];

export type GetSearchManifestApiV1ServicesSearchManifestGetResponses = {
  /**
   * Response Get Search Manifest Api V1 Services Search Manifest Get
   *
   * Successful Response
   */
  200: Array<SuggestionsResponse>;
};

export type GetSearchManifestApiV1ServicesSearchManifestGetResponse =
  GetSearchManifestApiV1ServicesSearchManifestGetResponses[keyof GetSearchManifestApiV1ServicesSearchManifestGetResponses];

export type SearchSuggestionsApiV1ServicesSuggestionsGetData = {
  body?: never;
  path?: never;
  query: {
    /**
     * Q
     */
    q: string;
  };
  url: "/api/v1/services/suggestions";
};

export type SearchSuggestionsApiV1ServicesSuggestionsGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type SearchSuggestionsApiV1ServicesSuggestionsGetError =
  SearchSuggestionsApiV1ServicesSuggestionsGetErrors[keyof SearchSuggestionsApiV1ServicesSuggestionsGetErrors];

export type SearchSuggestionsApiV1ServicesSuggestionsGetResponses = {
  /**
   * Response Search Suggestions Api V1 Services Suggestions Get
   *
   * Successful Response
   */
  200: Array<SuggestionsResponse>;
};

export type SearchSuggestionsApiV1ServicesSuggestionsGetResponse =
  SearchSuggestionsApiV1ServicesSuggestionsGetResponses[keyof SearchSuggestionsApiV1ServicesSuggestionsGetResponses];

export type GetTrendingServicesApiV1ServicesTrendingGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/services/trending";
};

export type GetTrendingServicesApiV1ServicesTrendingGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetTrendingServicesApiV1ServicesTrendingGetError =
  GetTrendingServicesApiV1ServicesTrendingGetErrors[keyof GetTrendingServicesApiV1ServicesTrendingGetErrors];

export type GetTrendingServicesApiV1ServicesTrendingGetResponses = {
  /**
   * Response Get Trending Services Api V1 Services Trending Get
   *
   * Successful Response
   */
  200: Array<SuggestionsResponse> | null;
};

export type GetTrendingServicesApiV1ServicesTrendingGetResponse =
  GetTrendingServicesApiV1ServicesTrendingGetResponses[keyof GetTrendingServicesApiV1ServicesTrendingGetResponses];

export type GetFiltersManifestApiV1ServicesFiltersManifestGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/api/v1/services/filters-manifest";
};

export type GetFiltersManifestApiV1ServicesFiltersManifestGetErrors = {
  /**
   * Not found
   */
  404: unknown;
};

export type GetFiltersManifestApiV1ServicesFiltersManifestGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetServicesByProviderApiV1ServicesServicesByProviderProviderGetData =
  {
    body?: never;
    path: {
      provider: ServiceProvider;
    };
    query?: never;
    url: "/api/v1/services/services-by-provider/{provider}";
  };

export type GetServicesByProviderApiV1ServicesServicesByProviderProviderGetErrors =
  {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type GetServicesByProviderApiV1ServicesServicesByProviderProviderGetError =
  GetServicesByProviderApiV1ServicesServicesByProviderProviderGetErrors[keyof GetServicesByProviderApiV1ServicesServicesByProviderProviderGetErrors];

export type GetServicesByProviderApiV1ServicesServicesByProviderProviderGetResponses =
  {
    /**
     * Response Get Services By Provider Api V1 Services Services By Provider  Provider  Get
     *
     * Successful Response
     */
    200: Array<ServiceRead>;
  };

export type GetServicesByProviderApiV1ServicesServicesByProviderProviderGetResponse =
  GetServicesByProviderApiV1ServicesServicesByProviderProviderGetResponses[keyof GetServicesByProviderApiV1ServicesServicesByProviderProviderGetResponses];

export type GetPublishedSlugsApiV1ServicesPublishedSlugsGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Limit
     */
    limit?: number;
  };
  url: "/api/v1/services/published-slugs";
};

export type GetPublishedSlugsApiV1ServicesPublishedSlugsGetErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPublishedSlugsApiV1ServicesPublishedSlugsGetError =
  GetPublishedSlugsApiV1ServicesPublishedSlugsGetErrors[keyof GetPublishedSlugsApiV1ServicesPublishedSlugsGetErrors];

export type GetPublishedSlugsApiV1ServicesPublishedSlugsGetResponses = {
  /**
   * Response Get Published Slugs Api V1 Services Published Slugs Get
   *
   * Successful Response
   */
  200: Array<string>;
};

export type GetPublishedSlugsApiV1ServicesPublishedSlugsGetResponse =
  GetPublishedSlugsApiV1ServicesPublishedSlugsGetResponses[keyof GetPublishedSlugsApiV1ServicesPublishedSlugsGetResponses];

export type RegisterServiceApiV1ServicesRegisterPostData = {
  body: ServiceCreateSchema;
  path?: never;
  query?: never;
  url: "/api/v1/services/register";
};

export type RegisterServiceApiV1ServicesRegisterPostErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterServiceApiV1ServicesRegisterPostError =
  RegisterServiceApiV1ServicesRegisterPostErrors[keyof RegisterServiceApiV1ServicesRegisterPostErrors];

export type RegisterServiceApiV1ServicesRegisterPostResponses = {
  /**
   * Successful Response
   */
  201: unknown;
};

export type IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostData =
  {
    body?: never;
    path: {
      /**
       * Slug
       */
      slug: string;
    };
    query?: never;
    url: "/api/v1/services/increment-popularity/{slug}";
  };

export type IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostErrors =
  {
    /**
     * Not found
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
  };

export type IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostError =
  IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostErrors[keyof IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostErrors];

export type IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostResponses =
  {
    /**
     * Successful Response
     */
    204: void;
  };

export type IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostResponse =
  IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostResponses[keyof IncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostResponses];

export type UpdateServiceApiV1ServicesUpdateSlugPutData = {
  body: ServiceUpdateSchema;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/api/v1/services/update/{slug}";
};

export type UpdateServiceApiV1ServicesUpdateSlugPutErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateServiceApiV1ServicesUpdateSlugPutError =
  UpdateServiceApiV1ServicesUpdateSlugPutErrors[keyof UpdateServiceApiV1ServicesUpdateSlugPutErrors];

export type UpdateServiceApiV1ServicesUpdateSlugPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteServiceApiV1ServicesDeleteSlugDeleteData = {
  body?: never;
  path: {
    /**
     * Slug
     */
    slug: string;
  };
  query?: never;
  url: "/api/v1/services/delete/{slug}";
};

export type DeleteServiceApiV1ServicesDeleteSlugDeleteErrors = {
  /**
   * Not found
   */
  404: unknown;
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteServiceApiV1ServicesDeleteSlugDeleteError =
  DeleteServiceApiV1ServicesDeleteSlugDeleteErrors[keyof DeleteServiceApiV1ServicesDeleteSlugDeleteErrors];

export type DeleteServiceApiV1ServicesDeleteSlugDeleteResponses = {
  /**
   * Successful Response
   */
  204: void;
};

export type DeleteServiceApiV1ServicesDeleteSlugDeleteResponse =
  DeleteServiceApiV1ServicesDeleteSlugDeleteResponses[keyof DeleteServiceApiV1ServicesDeleteSlugDeleteResponses];

export type TestCrashTestCrashGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/__test_crash__";
};

export type TestCrashTestCrashGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type HealthCheckHealthGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/health";
};

export type HealthCheckHealthGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type SeedDataSeedDataGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/seed_data";
};

export type SeedDataSeedDataGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};
