// This file is auto-generated by @hey-api/openapi-ts

import * as z from "zod";

/**
 * FAQ
 */
export const zFaq = z.object({
  q: z.string(),
  a: z.string(),
});

/**
 * OrderRequestSchema
 */
export const zOrderRequestSchema = z.object({
  userId: z.uuid(),
  serviceId: z.uuid(),
  name: z.string(),
  amount: z.int(),
});

/**
 * OrderStatus
 */
export const zOrderStatus = z.enum([
  "Pending",
  "Paid",
  "In Progress",
  "Completed",
  "Cancelled",
]);

/**
 * OrderUpdateSchema
 */
export const zOrderUpdateSchema = z.object({
  status: zOrderStatus,
});

/**
 * Pricing
 */
export const zPricing = z.object({
  governmentFee: z.optional(z.int()).default(0),
  serviceFee: z.optional(z.int()).default(0),
  total: z.optional(z.int()).default(0),
});

/**
 * ServiceCategory
 */
export const zServiceCategory = z.enum([
  "Transport & Motoring",
  "Civil Registration",
  "Taxation & KRA",
  "Business & Industry",
  "Education & Training",
  "Health Services",
  "Legal & Public Safety",
  "Lands & Housing",
  "Immigration & Foreign Affairs",
]);

/**
 * ServiceProvider
 */
export const zServiceProvider = z.enum([
  "Kenya Revenue Authority",
  "National Transport and Safety Authority",
  "Directorate of Criminal Investigations",
  "Business Registration Service",
  "Higher Education Loans Board",
  "Social Health Authority",
  "Department of Immigration",
  "Ministry of Lands",
  "Civil Registration Services",
]);

/**
 * ServiceCreateSchema
 */
export const zServiceCreateSchema = z.object({
  name: z.string(),
  slug: z.string(),
  provider: zServiceProvider,
  category: zServiceCategory,
  sub_category: z.string(),
  icon: z.string(),
  description: z.string(),
  seo_title: z.string(),
  seo_description: z.string(),
  requirements: z.array(z.string()),
  faqs: z.array(zFaq),
  pricing: zPricing,
  estimated_time: z.string(),
  available: z.optional(z.boolean()).default(true),
  published: z.optional(z.boolean()).default(false),
  featured: z.optional(z.boolean()).default(false),
  popularityScore: z.optional(z.union([z.number(), z.null()])).default(0),
  schemaType: z.optional(z.string()).default("Service"),
  relatedSlugs: z
    .optional(z.union([z.array(z.string()), z.null()]))
    .default([]),
});

/**
 * ServiceRead
 *
 * The schema Next.js uses for pre-rendering.
 */
export const zServiceRead = z.object({
  name: z.string(),
  slug: z.string(),
  provider: zServiceProvider,
  category: zServiceCategory,
  subCategory: z.string(),
  icon: z.string(),
  description: z.string(),
  seoTitle: z.string(),
  seoDescription: z.string(),
  requirements: z.array(z.string()),
  faqs: z.array(zFaq),
  pricing: zPricing,
  estimatedTime: z.string(),
  available: z.boolean(),
  published: z.boolean(),
  featured: z.optional(z.boolean()).default(false),
  popularityScore: z.optional(z.union([z.number(), z.null()])).default(0),
  schemaType: z.optional(z.string()).default("Service"),
  relatedSlugs: z
    .optional(z.union([z.array(z.string()), z.null()]))
    .default([]),
  id: z.uuid(),
});

/**
 * ServiceUpdateSchema
 */
export const zServiceUpdateSchema = z.object({
  name: z.optional(z.union([z.string(), z.null()])),
  slug: z.optional(z.union([z.string(), z.null()])),
  provider: z.optional(z.union([zServiceProvider, z.null()])),
  category: z.optional(z.union([zServiceCategory, z.null()])),
  sub_category: z.optional(z.union([z.string(), z.null()])),
  icon: z.optional(z.union([z.string(), z.null()])),
  description: z.optional(z.union([z.string(), z.null()])),
  seo_title: z.optional(z.union([z.string(), z.null()])),
  seo_description: z.optional(z.union([z.string(), z.null()])),
  requirements: z.optional(z.union([z.array(z.string()), z.null()])),
  faqs: z.optional(z.union([z.array(zFaq), z.null()])),
  pricing: z.optional(z.union([zPricing, z.null()])),
  estimated_time: z.optional(z.union([z.string(), z.null()])),
});

/**
 * StkRequest
 */
export const zStkRequest = z.object({
  phone: z.string(),
  amount: z.int(),
  reference: z.string(),
  description: z.optional(z.string()).default("Payment via M-Pesa"),
});

/**
 * SuggestionsResponse
 */
export const zSuggestionsResponse = z.object({
  n: z.optional(z.union([z.string(), z.null()])),
  s: z.optional(z.union([z.string(), z.null()])),
  c: z.optional(z.union([zServiceCategory, z.null()])),
  d: z.optional(z.string()),
  p: z.union([z.number(), z.null()]),
});

/**
 * TransactionRead
 */
export const zTransactionRead = z.object({
  phoneNumber: z.string(),
  amount: z.int(),
  reference: z.string(),
  checkoutRequestId: z.string(),
  merchantRequestId: z.string(),
  mpesaReceiptNumber: z.optional(z.union([z.string(), z.null()])),
  resultCode: z.optional(z.int()).default(-1),
  resultDesc: z.optional(z.union([z.string(), z.null()])),
  status: z.optional(z.union([zOrderStatus, z.null()])),
});

/**
 * UserCreateSchema
 */
export const zUserCreateSchema = z.object({
  firstName: z.string(),
  secondName: z.string(),
  email: z.email(),
  phoneNumber: z.string(),
  contactMethod: z.string(),
});

/**
 * UserRead
 */
export const zUserRead = z.object({
  firstName: z.string(),
  secondName: z.string(),
  email: z.email(),
  phoneNumber: z.string(),
  contactMethod: z.string(),
  id: z.uuid(),
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
  loc: z.array(z.union([z.string(), z.int()])),
  msg: z.string(),
  type: z.string(),
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
  detail: z.optional(z.array(zValidationError)),
});

export const zGetTransApiV1PaymentsTransactionsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      checkout_request_id: z.optional(z.string()),
      limit: z.optional(z.int()).default(50),
    }),
  ),
});

/**
 * Response Get Trans Api V1 Payments Transactions Get
 *
 * Successful Response
 */
export const zGetTransApiV1PaymentsTransactionsGetResponse = z.union([
  zTransactionRead,
  z.array(zTransactionRead),
]);

export const zInitiateStkPushApiV1PaymentsStkPushPostData = z.object({
  body: zStkRequest,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPaymentsValidationApiV1PaymentsValidationPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPaymentsConfirmationApiV1PaymentsConfirmationPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zPaymentsStkCallbackApiV1PaymentsStkCallbackPostData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zReadUsersApiV1UsersGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      user_id: z.optional(z.string()),
      email: z.optional(z.email()),
      limit: z.optional(z.int()).default(50),
    }),
  ),
});

/**
 * Response Read Users Api V1 Users  Get
 *
 * Successful Response
 */
export const zReadUsersApiV1UsersGetResponse = z.union([
  zUserRead,
  z.array(zUserRead),
]);

export const zCreateUserApiV1UsersRegisterPostData = z.object({
  body: zUserCreateSchema,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetOrdersApiV1OrdersFilteredGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      user_id: z.optional(z.uuid()),
      status: z.optional(zOrderStatus),
      limit: z.optional(z.int()).default(50),
    }),
  ),
});

export const zGetOrderIdApiV1OrdersOrderIdGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    order_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zCreateOrderApiV1OrdersCreatePostData = z.object({
  body: zOrderRequestSchema,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zUpdateOrderApiV1OrdersUpdateOrderIdPutData = z.object({
  body: zOrderUpdateSchema,
  path: z.object({
    order_id: z.uuid(),
  }),
  query: z.optional(z.never()),
});

export const zGetServicesApiV1ServicesFilteredGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      category: z.optional(z.union([zServiceCategory, z.null()])),
      provider: z.optional(z.union([zServiceProvider, z.null()])),
      skip: z.optional(z.int()).default(0),
      limit: z.optional(z.int()).default(100),
    }),
  ),
});

/**
 * Response Get Services Api V1 Services Filtered Get
 *
 * Successful Response
 */
export const zGetServicesApiV1ServicesFilteredGetResponse =
  z.array(zServiceRead);

export const zGetServiceBySlugApiV1ServicesBySlugSlugGetData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    slug: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zGetServiceBySlugApiV1ServicesBySlugSlugGetResponse = zServiceRead;

export const zGetSearchManifestApiV1ServicesSearchManifestGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.int()).default(200),
    }),
  ),
});

/**
 * Response Get Search Manifest Api V1 Services Search Manifest Get
 *
 * Successful Response
 */
export const zGetSearchManifestApiV1ServicesSearchManifestGetResponse =
  z.array(zSuggestionsResponse);

export const zSearchSuggestionsApiV1ServicesSuggestionsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.object({
    q: z.string().min(3),
  }),
});

/**
 * Response Search Suggestions Api V1 Services Suggestions Get
 *
 * Successful Response
 */
export const zSearchSuggestionsApiV1ServicesSuggestionsGetResponse =
  z.array(zSuggestionsResponse);

export const zGetTrendingServicesApiV1ServicesTrendingGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.int()).default(5),
    }),
  ),
});

/**
 * Response Get Trending Services Api V1 Services Trending Get
 *
 * Successful Response
 */
export const zGetTrendingServicesApiV1ServicesTrendingGetResponse = z.union([
  z.array(zSuggestionsResponse),
  z.null(),
]);

export const zGetFiltersManifestApiV1ServicesFiltersManifestGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zGetServicesByProviderApiV1ServicesServicesByProviderProviderGetData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      provider: zServiceProvider,
    }),
    query: z.optional(z.never()),
  });

/**
 * Response Get Services By Provider Api V1 Services Services By Provider  Provider  Get
 *
 * Successful Response
 */
export const zGetServicesByProviderApiV1ServicesServicesByProviderProviderGetResponse =
  z.array(zServiceRead);

export const zGetPublishedSlugsApiV1ServicesPublishedSlugsGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(
    z.object({
      limit: z.optional(z.int()).default(100),
    }),
  ),
});

/**
 * Response Get Published Slugs Api V1 Services Published Slugs Get
 *
 * Successful Response
 */
export const zGetPublishedSlugsApiV1ServicesPublishedSlugsGetResponse = z.array(
  z.string(),
);

export const zRegisterServiceApiV1ServicesRegisterPostData = z.object({
  body: zServiceCreateSchema,
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zIncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostData =
  z.object({
    body: z.optional(z.never()),
    path: z.object({
      slug: z.string(),
    }),
    query: z.optional(z.never()),
  });

/**
 * Successful Response
 */
export const zIncrementServicePopularityApiV1ServicesIncrementPopularitySlugPostResponse =
  z.void();

export const zUpdateServiceApiV1ServicesUpdateSlugPutData = z.object({
  body: zServiceUpdateSchema,
  path: z.object({
    slug: z.string(),
  }),
  query: z.optional(z.never()),
});

export const zDeleteServiceApiV1ServicesDeleteSlugDeleteData = z.object({
  body: z.optional(z.never()),
  path: z.object({
    slug: z.string(),
  }),
  query: z.optional(z.never()),
});

/**
 * Successful Response
 */
export const zDeleteServiceApiV1ServicesDeleteSlugDeleteResponse = z.void();

export const zTestCrashTestCrashGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zHealthCheckHealthGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});

export const zSeedDataSeedDataGetData = z.object({
  body: z.optional(z.never()),
  path: z.optional(z.never()),
  query: z.optional(z.never()),
});
