from app.lib.db.models import ServiceProvider, ServiceCategory

services = [
    {
        "name": "New KRA PIN Registration",
        "slug": "new-kra-pin-registration-kenya",
        "provider": ServiceProvider.KRA,
        "category": ServiceCategory.TAXATION,
        "subCategory": "ITax Registration",
        "icon": "💎",
        "description": "Apply for your KRA PIN certificate online in Kenya. Our professional agents ensure your iTax registration is handled accurately.",
        "seoTitle": "KRA PIN Registration Online Kenya | Get Your PIN Fast",
        "seoDescription": "Need a KRA PIN for a bank account or job? Get your KRA PIN certificate online in minutes.",
        "requirements": [
            "National ID Card / Passport",
            "Valid Email Address",
            "Active Kenyan Phone Number",
            "Physical Address details",
        ],
        "faqs": [
            {
                "q": "Can I get a KRA PIN without an ID?",
                "a": "No, a valid National ID or Passport is required.",
            },
            {
                "q": "How long does it take?",
                "a": "Most registrations are completed within 30 minutes to 2 hours.",
            },
        ],
        "pricing": {"governmentFee": 0, "serviceFee": 200, "total": 200},
        "estimatedTime": "30 mins – 2 hours",
    },
    {
        "name": "Lost KRA PIN Recovery",
        "slug": "recover-lost-kra-pin-kenya",
        "provider": ServiceProvider.KRA,
        "category": ServiceCategory.TAXATION,
        "subCategory": "ITax Recovery",
        "icon": "🔑",
        "description": "Lost your KRA PIN or forgot your iTax login credentials? We recover forgotten KRA PINs through the official iTax system.",
        "seoTitle": "Recover Lost KRA PIN & Password | iTax Recovery Kenya",
        "seoDescription": "Lost your KRA PIN certificate or iTax password? We help you recover your tax details quickly.",
        "requirements": ["National ID Number", "Full Name as per ID"],
        "faqs": [
            {
                "q": "What if I don't have access to my registered email?",
                "a": "We assist in the email change process through KRA.",
            },
        ],
        "pricing": {"governmentFee": 0, "serviceFee": 300, "total": 300},
        "estimatedTime": "30 – 60 minutes",
    },
    {
        "name": "File KRA Returns",
        "slug": "file-kra-returns-kenya",
        "provider": ServiceProvider.KRA,
        "category": ServiceCategory.TAXATION,
        "subCategory": "Annual Returns",
        "icon": "📝",
        "description": "Ensure your KRA Nil returns or Employment returns are filed accurately and on time.",
        "seoTitle": "File KRA Returns Online 2026 | Nil & Employment Returns",
        "seoDescription": "Avoid KRA penalties by filing your 2026 tax returns today. We handle Nil and P9 returns accurately.",
        "requirements": ["KRA PIN", "iTax Password", "P9 Form (if employed)"],
        "faqs": [
            {
                "q": "What is the penalty for late filing?",
                "a": "The penalty for individuals is KES 2,000 per year.",
            },
        ],
        "pricing": {"governmentFee": 0, "serviceFee": 100, "total": 100},
        "estimatedTime": "Same day",
    },
    {
        "name": "Driving Licence Renewal",
        "slug": "ntsa-driving-licence-renewal",
        "provider": ServiceProvider.NTSA,
        "category": ServiceCategory.TRANSPORT,
        "subCategory": "DL Renewal",
        "icon": "🚗",
        "description": "Stay legal on Kenyan roads with our fast NTSA Driving Licence renewal service via the eCitizen portal.",
        "seoTitle": "NTSA Driving License Renewal Kenya | 1 & 3 Year Renewal",
        "seoDescription": "Renew your Kenyan Driving License online. Fast eCitizen NTSA processing for 1-year and 3-year DL renewals.",
        "requirements": [
            "Original Driving Licence",
            "eCitizen Account Access",
            "National ID",
        ],
        "faqs": [
            {
                "q": "How much does NTSA charge for 3 years?",
                "a": "The government fee for a 3-year renewal is KES 3,050.",
            },
        ],
        "pricing": {"governmentFee": 3050, "serviceFee": 250, "total": 3300},
        "estimatedTime": "Same day – 2 days",
    },
    {
        "name": "Motor Vehicle Transfer",
        "slug": "ntsa-motor-vehicle-transfer-kenya",
        "provider": ServiceProvider.NTSA,
        "category": ServiceCategory.TRANSPORT,
        "subCategory": "Logbook Transfer",
        "icon": "🔄",
        "description": "End-to-end assistance with NTSA motor vehicle ownership transfer through the TIMS/eCitizen portal.",
        "seoTitle": "Logbook Transfer Kenya | NTSA Motor Vehicle Transfer",
        "seoDescription": "Professional assistance for NTSA logbook transfers. We ensure buyer and seller complete requirements correctly.",
        "requirements": [
            "Logbook (Scan/Copy)",
            "Buyer/Seller ID & KRA PIN",
            "Sales Agreement",
        ],
        "faqs": [
            {
                "q": "Do both parties need eCitizen?",
                "a": "Yes, both parties must have active eCitizen accounts.",
            },
        ],
        "pricing": {"governmentFee": 3000, "serviceFee": 1000, "total": 4000},
        "estimatedTime": "2 – 5 business days",
    },
    {
        "name": "Good Conduct (Police Clearance)",
        "slug": "good-conduct-police-clearance-kenya",
        "provider": ServiceProvider.DCI,
        "category": ServiceCategory.LEGAL,
        "subCategory": "Clearance Certificates",
        "icon": "📜",
        "description": "Apply for your Certificate of Good Conduct for employment or travel. We handle application and booking.",
        "seoTitle": "Apply for Certificate of Good Conduct Kenya | DCI Clearance",
        "seoDescription": "Get your Police Clearance Certificate easily. We assist with application and DCI fingerprint booking.",
        "requirements": [
            "National ID Card",
            "Original Fingerprint processing",
            "eCitizen Login",
        ],
        "faqs": [
            {
                "q": "Where do I take fingerprints?",
                "a": "Choose your nearest DCI headquarters or Huduma Center during booking.",
            },
        ],
        "pricing": {"governmentFee": 1050, "serviceFee": 200, "total": 1250},
        "estimatedTime": "2 – 4 weeks",
    },
    {
        "name": "HELB Loan Application",
        "slug": "helb-loan-application-assistance",
        "provider": ServiceProvider.HELB,
        "category": ServiceCategory.EDUCATION,
        "subCategory": "Student Financing",
        "icon": "🎓",
        "description": "Professional guidance for first-time or subsequent HELB loan applications to maximize success.",
        "seoTitle": "HELB Loan Application Help | University Funding Kenya",
        "seoDescription": "Need help applying for HELB? We guide you through the student portal and guarantor details.",
        "requirements": [
            "HELB Smart Card/Account",
            "Guarantors' IDs",
            "Admission Letter",
        ],
        "faqs": [
            {
                "q": "Is HELB only for University students?",
                "a": "No, HELB also provides loans for TVET and College students.",
            },
        ],
        "pricing": {"governmentFee": 0, "serviceFee": 300, "total": 300},
        "estimatedTime": "1 – 2 hours",
    },
    {
        "name": "NTSA Smart DL Application",
        "slug": "ntsa-smart-driving-license-application-kenya",
        "provider": ServiceProvider.NTSA,
        "category": ServiceCategory.TRANSPORT,
        "subCategory": "Smart DL",
        "icon": "🪪",
        "description": "Upgrade to the new generation NTSA Smart Driving License. We assist with TIMS/eCitizen account setup, payment processing, and biometric booking.",
        "seoTitle": "Apply for NTSA Smart DL Kenya | New Digital Driving License",
        "seoDescription": "Apply for your Kenyan Smart Driving License today. Get help with eCitizen booking, biometric capture, and tracking status.",
        "requirements": [
            "Original ID Card",
            "Copy of Current DL (for upgrades)",
            "eCitizen / TIMS Account Access",
            "Blood Group Information",
            "KRA PIN",
        ],
        "faqs": [
            {
                "q": "How much is the Smart DL fee?",
                "a": "The official NTSA fee for the Smart DL is KES 3,050.",
            },
            {
                "q": "How long does it take?",
                "a": "Typically 5–10 working days after biometric capture.",
            },
        ],
        "pricing": {"governmentFee": 3050, "serviceFee": 500, "total": 3550},
        "estimatedTime": "5 – 10 business days",
    },
    {
        "name": "Social Health Authority (SHA) Registration",
        "slug": "sha-registration-shif-kenya",
        "provider": ServiceProvider.SHA,
        "category": ServiceCategory.HEALTH,
        "subCategory": "Medical Insurance",
        "icon": "🏥",
        "description": "Register for the Social Health Authority (SHA/SHIF), which has replaced NHIF. Our agents help with registration and household means-testing.",
        "seoTitle": "Register for SHA Kenya Online | SHIF Enrollment Guide 2026",
        "seoDescription": "Transition from NHIF to SHA today. Learn how to register for SHIF online and add your dependents.",
        "requirements": [
            "National ID Number",
            "Active Mobile Number",
            "Spouse ID (if adding dependents)",
            "Children's Birth Certificates",
        ],
        "faqs": [
            {
                "q": "Is registration mandatory?",
                "a": "Yes, every Kenyan resident is required by law to register for SHA.",
            },
            {
                "q": "What about my old NHIF?",
                "a": "NHIF has transitioned to SHA; you must re-register under the new system.",
            },
        ],
        "pricing": {"governmentFee": 0, "serviceFee": 200, "total": 200},
        "estimatedTime": "15 – 30 minutes",
    },
    {
        "name": "Passport Application & Renewal",
        "slug": "kenya-passport-application-renewal-online",
        "provider": ServiceProvider.IMMIGRATION,
        "category": ServiceCategory.IMMIGRATION,
        "subCategory": "Travel Documents",
        "icon": "🛂",
        "description": "Apply for a new Kenyan E-Passport or renew your expired one. We handle eCitizen application and biometric booking.",
        "seoTitle": "Kenya Passport Application 2026 | Renewal & New Passport Guide",
        "seoDescription": "Need a Kenyan passport fast? Apply online for 32, 48, or 64-page e-passports. We assist with booking.",
        "requirements": [
            "Original Birth Certificate",
            "National ID Card",
            "Previous Passport (for renewals)",
            "Parents' ID Copies",
            "Recommender ID Copy",
        ],
        "faqs": [
            {
                "q": "How much is a 32-page passport?",
                "a": "The government fee is KES 4,550 for the A-series.",
            },
            {
                "q": "Can I track my status?",
                "a": "Yes, trackable via your eCitizen portal after biometrics.",
            },
        ],
        "pricing": {"governmentFee": 4550, "serviceFee": 1000, "total": 5550},
        "estimatedTime": "4 – 8 weeks",
    },
    {
        "name": "Business Name Registration",
        "slug": "business-name-registration-kenya-brs",
        "provider": ServiceProvider.BRS,
        "category": ServiceCategory.BUSINESS,
        "subCategory": "Sole Proprietorship",
        "icon": "🏢",
        "description": "Register your business name (BN2) through the BRS on eCitizen. Perfect for sole proprietorships.",
        "seoTitle": "Register a Business Name in Kenya | eCitizen BRS Guide",
        "seoDescription": "Formalize your business today. Register your business name online. We handle name search and certificate.",
        "requirements": [
            "Three Unique Business Names",
            "Nature of Business",
            "Proprietor ID & KRA PIN",
            "Physical Address",
        ],
        "faqs": [
            {"q": "What is the cost?", "a": "The government fee is KES 950."},
            {
                "q": "How long does it take?",
                "a": "Name approval usually takes 24–48 hours.",
            },
        ],
        "pricing": {"governmentFee": 950, "serviceFee": 550, "total": 1500},
        "estimatedTime": "2 – 3 business days",
    },
    {
        "name": "Tax Compliance Certificate (TCC)",
        "slug": "apply-kra-tax-compliance-certificate-tcc",
        "provider": ServiceProvider.KRA,
        "category": ServiceCategory.TAXATION,
        "subCategory": "Compliance",
        "icon": "📜",
        "description": "Apply for your KRA Tax Compliance Certificate (TCC). We review your iTax ledger to ensure no pending returns.",
        "seoTitle": "Apply for KRA TCC Online | Tax Compliance Certificate 2026",
        "seoDescription": "Need a TCC for a tender? Apply for your KRA Tax Compliance Certificate online. We help resolve pending tax issues.",
        "requirements": ["KRA PIN", "iTax Password", "All Returns Filed to Date"],
        "faqs": [
            {
                "q": "Why was my TCC rejected?",
                "a": "Usually due to unfiled returns or unpaid penalties.",
            },
            {"q": "How long is it valid?", "a": "TCC is valid for twelve (12) months."},
        ],
        "pricing": {"governmentFee": 0, "serviceFee": 200, "total": 200},
        "estimatedTime": "Same day",
    },
    # --- ADDITIONAL HIGH-DEMAND SERVICES ---
    {
        "name": "NTSA Vehicle Inspection",
        "slug": "ntsa-vehicle-inspection-booking",
        "provider": ServiceProvider.NTSA,
        "category": ServiceCategory.TRANSPORT,
        "subCategory": "Inspection",
        "icon": "🔍",
        "description": "Book your annual vehicle inspection with NTSA. We handle the eCitizen booking and payment for all centers.",
        "seoTitle": "NTSA Vehicle Inspection Kenya | Book Inspection Online",
        "seoDescription": "Book your NTSA vehicle inspection online. Fast eCitizen processing for commercial and private vehicle inspections.",
        "requirements": ["Original Logbook", "Vehicle Details", "Owner ID"],
        "faqs": [
            {
                "q": "Where is the inspection done?",
                "a": "At your selected NTSA inspection center during booking.",
            }
        ],
        "pricing": {"governmentFee": 1050, "serviceFee": 450, "total": 1500},
        "estimatedTime": "1 – 2 days",
    },
    {
        "name": "Birth Certificate Application",
        "slug": "apply-birth-certificate-kenya",
        "provider": ServiceProvider.CRS,
        "category": ServiceCategory.CIVIL_REG,
        "subCategory": "Vital Records",
        "icon": "👶",
        "description": "Apply for a new or replacement birth certificate online via eCitizen CRS portal.",
        "seoTitle": "Birth Certificate Kenya | Apply Online via eCitizen",
        "seoDescription": "Get your child's birth certificate or replace a lost one. We guide you through the CRS portal application.",
        "requirements": ["Notification of Birth", "Parents' IDs", "Clinic Card"],
        "faqs": [
            {
                "q": "How long does it take?",
                "a": "Processing at Sheria House takes 1–4 weeks.",
            }
        ],
        "pricing": {"governmentFee": 200, "serviceFee": 300, "total": 500},
        "estimatedTime": "1 – 4 weeks",
    },
]
